"use client";

import { useActionState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Link as LocalizedLink } from "@/i18n/navigation";
import type { CertDrillAdminCategory, CertDrillAdminCertification, CertDrillAdminExamForm, CertDrillAdminQuestion } from "@/lib/api/certdrill.server";
import { initialExamFormActionState } from "./exam-form-action-error";
import { regenerateCertDrillExamFormAction, replaceCertDrillExamFormQuestionAction, setCertDrillExamFormActiveAction, updateCertDrillExamFormMetadataAction } from "./exam-form-actions";
import { examFormListHref } from "./exam-form-href";

export function ExamFormEditor({ certification, categories, questions, examForm }: { certification: CertDrillAdminCertification; categories: CertDrillAdminCategory[]; questions: CertDrillAdminQuestion[]; examForm: CertDrillAdminExamForm }) {
  const categoriesById = new Map(categories.map((category) => [category.id, category]));
  const questionsById = new Map(questions.map((question) => [question.id, question]));
  const rootId = (categoryId: string) => { let current = categoriesById.get(categoryId); const seen = new Set<string>(); while (current) { if (current.archivedAt || seen.has(current.id)) return null; seen.add(current.id); if (!current.parentCategoryId) return current.id; current = categoriesById.get(current.parentCategoryId); } return null; };
  const assignedQuestionsByTopLevelCategory = new Map<string, CertDrillAdminQuestion[]>();
  for (const id of examForm.questionIds) { const question = questionsById.get(id); const root = question ? rootId(question.categoryId) : null; if (question && root) assignedQuestionsByTopLevelCategory.set(root, [...(assignedQuestionsByTopLevelCategory.get(root) ?? []), question]); }
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><Badge variant="secondary">Exam form editor</Badge><h1 className="mt-3 text-3xl font-bold tracking-tight">{examForm.name}</h1><p className="mt-2 text-muted-foreground">{certification.code} · {examForm.targetQuestionCount} questions · {examForm.durationMinutes} minutes</p></div><Button asChild variant="outline"><LocalizedLink href={examFormListHref(certification.id)}>Back to Exam Forms</LocalizedLink></Button></div>
    {examForm.description ? <Card><CardHeader><CardTitle>Description</CardTitle></CardHeader><CardContent className="whitespace-pre-wrap text-sm text-muted-foreground">{examForm.description}</CardContent></Card> : null}
    <div className="grid gap-4 xl:grid-cols-[2fr_1fr]"><MetadataCard certificationId={certification.id} examForm={examForm} /><AssignmentActions certificationId={certification.id} examForm={examForm} /></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{examForm.allocationSnapshot.map((allocation) => <Card key={allocation.categoryId}><CardHeader className="pb-2"><CardDescription>{allocation.categoryName}</CardDescription><CardTitle>{allocation.assignedCount} questions</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{allocation.weightPct}% weight · {((allocation.assignedCount / examForm.targetQuestionCount) * 100).toFixed(2)}% of form</CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle>Assigned questions</CardTitle><CardDescription>Questions are grouped for review without changing their persisted order.</CardDescription></CardHeader><CardContent><Tabs defaultValue={examForm.allocationSnapshot[0]?.categoryId}>{<TabsList className="mb-4 flex h-auto flex-wrap justify-start">{examForm.allocationSnapshot.map((allocation) => <TabsTrigger key={allocation.categoryId} value={allocation.categoryId}>{allocation.categoryName}</TabsTrigger>)}</TabsList>}{examForm.allocationSnapshot.map((allocation) => <TabsContent key={allocation.categoryId} value={allocation.categoryId}><QuestionTable questions={assignedQuestionsByTopLevelCategory.get(allocation.categoryId) ?? []} categoriesById={categoriesById} alternatives={questions.filter((question) => question.status === "published" && rootId(question.categoryId) === allocation.categoryId && !examForm.questionIds.includes(question.id))} certificationId={certification.id} examForm={examForm} /></TabsContent>)}</Tabs></CardContent></Card>
  </div>;
}

function MetadataCard({ certificationId, examForm }: { certificationId: string; examForm: CertDrillAdminExamForm }) {
  const [state, action, pending] = useActionState(updateCertDrillExamFormMetadataAction, initialExamFormActionState);
  return <Card><CardHeader><CardTitle>Details</CardTitle><CardDescription>Name and duration changes preserve the assignment.</CardDescription></CardHeader><CardContent><form action={action} className="grid gap-4 sm:grid-cols-2"><Hidden certificationId={certificationId} examForm={examForm} /><div className="space-y-2"><Label htmlFor="form-name">Name</Label><Input id="form-name" name="name" defaultValue={examForm.name} required /></div><div className="space-y-2"><Label htmlFor="form-duration">Duration minutes</Label><Input id="form-duration" name="durationMinutes" type="number" min="1" defaultValue={examForm.durationMinutes} required /></div>{state.formError ? <p role="alert" className="text-sm text-destructive sm:col-span-2">{state.formError}</p> : null}<Button className="sm:col-span-2 sm:w-fit" disabled={pending}>Save details</Button></form></CardContent></Card>;
}

function AssignmentActions({ certificationId, examForm }: { certificationId: string; examForm: CertDrillAdminExamForm }) {
  const [regenState, regenerate, regenPending] = useActionState(regenerateCertDrillExamFormAction, initialExamFormActionState);
  const [activeState, activate, activePending] = useActionState(setCertDrillExamFormActiveAction, initialExamFormActionState);
  return <Card><CardHeader><CardTitle>Assignment</CardTitle><CardDescription><Badge variant={examForm.isActive ? "default" : "secondary"}>{examForm.isActive ? "Active" : "Inactive"}</Badge></CardDescription></CardHeader><CardContent className="space-y-5"><form action={regenerate} onSubmit={(event) => { if (!window.confirm(event.currentTarget.targetQuestionCount.value === String(examForm.targetQuestionCount) ? "Regenerating replaces all assigned questions and discards manual swaps. Continue?" : "Changing the question count replaces all assigned questions. Continue?")) event.preventDefault(); }} className="space-y-3"><Hidden certificationId={certificationId} examForm={examForm} version /><Label htmlFor="target-count">Target question count</Label><Input id="target-count" name="targetQuestionCount" type="number" min="1" defaultValue={examForm.targetQuestionCount} /><p className="text-xs text-muted-foreground">Changing the question count replaces all assigned questions.</p>{regenState.formError ? <p className="text-sm text-destructive">{regenState.formError}</p> : null}<Button type="submit" variant="outline" disabled={regenPending}>Regenerate Questions</Button></form><form action={activate}><Hidden certificationId={certificationId} examForm={examForm} /><input type="hidden" name="isActive" value={String(!examForm.isActive)} />{activeState.formError ? <p className="mb-2 text-sm text-destructive">{activeState.formError}</p> : null}<Button disabled={activePending} variant={examForm.isActive ? "outline" : "default"}>{examForm.isActive ? "Deactivate" : "Activate"}</Button></form></CardContent></Card>;
}

function QuestionTable({ questions, categoriesById, alternatives, certificationId, examForm }: { questions: CertDrillAdminQuestion[]; categoriesById: Map<string, CertDrillAdminCategory>; alternatives: CertDrillAdminQuestion[]; certificationId: string; examForm: CertDrillAdminExamForm }) {
  return <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Question</TableHead><TableHead>Direct category</TableHead><TableHead>Difficulty</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{questions.map((question) => <TableRow key={question.id}><TableCell className="max-w-xl whitespace-normal">{question.stem}</TableCell><TableCell>{categoriesById.get(question.categoryId)?.name ?? question.categoryId}</TableCell><TableCell>{question.difficulty ?? "medium"}</TableCell><TableCell><Badge variant="outline">{question.status}</Badge></TableCell><TableCell className="text-right"><ReplaceDialog current={question} alternatives={alternatives} certificationId={certificationId} examForm={examForm} /></TableCell></TableRow>)}</TableBody></Table></div>;
}

function ReplaceDialog({ current, alternatives, certificationId, examForm }: { current: CertDrillAdminQuestion; alternatives: CertDrillAdminQuestion[]; certificationId: string; examForm: CertDrillAdminExamForm }) {
  const [state, action, pending] = useActionState(replaceCertDrillExamFormQuestionAction, initialExamFormActionState);
  if (!alternatives.length) return <div className="inline-flex flex-col items-end gap-1"><Button size="sm" variant="outline" disabled>Replace</Button><span className="max-w-48 text-xs text-muted-foreground">No eligible replacement is available.</span></div>;
  return <Dialog><DialogTrigger asChild><Button size="sm" variant="outline">Replace</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Replace question</DialogTitle><DialogDescription>Choose a published, unassigned question from the same top-level category.</DialogDescription></DialogHeader><form action={action} className="space-y-4"><Hidden certificationId={certificationId} examForm={examForm} version /><input type="hidden" name="currentQuestionId" value={current.id} /><div className="space-y-2"><Label htmlFor={`replacement-${current.id}`}>Replacement</Label><select id={`replacement-${current.id}`} name="replacementQuestionId" className="w-full rounded-md border bg-background p-2" required>{alternatives.map((question) => <option key={question.id} value={question.id}>{question.stem}</option>)}</select></div>{state.formError ? <p className="text-sm text-destructive">{state.formError}</p> : null}<Button disabled={pending}>Replace</Button></form></DialogContent></Dialog>;
}

function Hidden({ certificationId, examForm, version = false }: { certificationId: string; examForm: CertDrillAdminExamForm; version?: boolean }) { return <><input type="hidden" name="certificationId" value={certificationId} /><input type="hidden" name="examFormId" value={examForm.id} />{version ? <input type="hidden" name="expectedAssignmentVersion" value={examForm.assignmentVersion} /> : null}</>; }
